.TH mail2pkt 1 "MAIL-to-PKT v0.2"
.SH NAME
mail2pkt \- converts email attachments to FTN packets
.SH SYNOPSIS
\fBmail2pkt\fP [\fBinbound\fP]
.SH DESCRIPTION
.I Mail-to-pkt
will read an email from the standard input and try to decode it
and write a FTN packet in your protected inbound, defined in
.I fidoconfig
or in an user selected directory. Currently, only base64 encoded files are
supported, but other encodings may be added in the future. It was designed
to be used as a procmail filter, thought it can be used in other ways such
as called from within scripts.
.SH OPTIONS
.TP
.I inbound
The directory where all incoming files will be stored. If not present, the
protected inbound from fidoconfig will be used. 
.SH EXAMPLES
See the provided procmailrc for a working configuration example.
.SH BUGS
There are a lot. Please send them to german@linuxfreak.com
.SH AUTHOR
German Theler - german@linuxfreak.com
